[Enhancement] finishing touches
bioinformatics-lab/wgs_lineage1_phylogenetic_nf pull request #3
Opened 2021-07-04 16:30 UTC by Mxrcon

Hey @abhi18av do you think that after the #2  got merged, and with this content, this pipeline is ready for a README with instructions? I'll add them to this PR and conclude my finishing touches. I've checked every module and found some errors. also, if I'll proceed adding test instructions to each module.

## PR content
* update to gitignore
* tweaks on trimommatic and tb_profiler_collate
* dag.png

## PR ending
Hope we have a merge! Feel free to discuss this changes with me, I'm at your disposal to make any necessary change.

2021-07-05 07:01 UTC, abhi18av requested changes
Thanks for the follow-up on this @Mxrcon  👏 

I have added some comments, mostly related to the patterns that we are following in this repo.

2021-07-05 07:01 UTC, abhi18av commented on modules/tb_profiler/tb_profiler_collate.nf
> +params.results_dir = "${params.outdir}/tb_profiler/collate"
This needs to be consistent with the module name and the file name.

The module name is `TBPROFILER_COLLATE` 
The filename should be `/modules/tbprofiler/collate.nf`
The `results_dir` name should be `tbprofiler/collate`.

2021-07-05 07:01 UTC, abhi18av commented on modules/trimmomatic/trimmomatic.nf
> +    def adapterFile = "/usr/local/share/trimmomatic-0.35-6/adapters/${params.adapter_file_name}"
This needs to be added to the `params.yml` file, also I think that perhaps we need to add a default value within the module as well.

For example

```
params.adapter_file_name = "NexteraPE-PE.fa"
```

2021-07-05 13:42 UTC, Mxrcon commented on modules/tb_profiler/tb_profiler_collate.nf
> +params.results_dir = "${params.outdir}/tb_profiler/collate"
ok! I'll fixup this output name

2021-07-06 02:05 UTC, Mxrcon commented
@abhi18av I think that my last commit updates the last requested changes, so I'm gently requesting  new review for this PR

2021-07-06 07:01 UTC, abhi18av approved these changes
Looks good to merge, thanks for accomodating the changes!

2021-07-06 07:01 UTC, merged